import Navbar from "@/components/Navbar";
import NavbarTeams from "@/components/NavbarTeams";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>
          <Navbar />
          <NavbarTeams />
          {children}
        </main>
      </body>
    </html>
  );
}
