import NavbarTeams from "@/components/NavbarTeams";

export const metadata = {
  title: "Teams",
  description: "Generated by create next app"
};

export default function TeamsLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <section>
      <NavbarTeams />
      {children}
    </section>
  );
}
